### ISSUE TITLE
Qoob Pro Slots Corrupted

### ISSUE THREAD

**Issue by Fgo988** [redolution/iplboot#17]
I used iplboot r6 before as Qoob Pro Bios to start directly into swiss.
Now i flashed iplboot r7 as Bios, but the Slots are marked as Corrupted and when I disconnect the Qoob this Error Message appers: No Bios flashed into Qoob! No boot possible.

With r6 the flasher worked like with the original Qoob Bios, no Slots marked as corrupted and no error message appers
Nevertheless I powered on the Gamecube an it seems to work. 
Is this only a problem with my Setup or is this normal and it can not be solved?

**Comment by 9ary** [comment]
That's strange. The message comes from the flasher right? And if you try flashing r6 again it still works? I wonder if it's just the new file header that's confusing the flasher. Let's see what happens if I revert that change.

Try this build when it finishes: https://github.com/redolution/iplboot/actions/runs/2769931103.

**Comment by 9ary** [comment]
For the record the official Qoob BIOS has the version string `(C) qoob bios 1.3c`, and previous iplboot builds used the unmodified version string from a PAL 1.0 IPL dump, which also begins with `(C) ...`, so that might be the culprit.

You should try this build as well: https://github.com/redolution/iplboot/actions/runs/2769972526.

**Comment by Fgo988** [comment]
With this build it seems to work perfectly. No Corrupted Slots anymore and no error Message.

**Comment by 9ary** [comment]
Which one did you try?

**Comment by Fgo988** [comment]
> For the record the official Qoob BIOS has the version string `(C) qoob bios 1.3c`, and previous iplboot builds used the unmodified version string from a PAL 1.0 IPL dump, which also begins with `(C) ...`, so that might be the culprit.
> 
> You should try this build as well: https://github.com/redolution/iplboot/actions/runs/2769972526. If this one works then that's what we'll go with.

This build.

**Comment by 9ary** [comment]
Thanks for testing. I will update the file on the releases page.
