### ISSUE TITLE
Can't bypass PicoBoot IPL to get default GC IPL

### ISSUE THREAD

**Issue by Koohiisan** [redolution/iplboot#37]
Per the directions, I tried holding reset when powering on, and I tried holding left on the D-pad when pressing power, but neither will boot into the original GameCube bios for me to access the memory cards/calendar/et al.  It immediately boots Swiss from my SD2SP2.

Am I misunderstanding and it's not possible to do a boot into the default GC bios like I am wanting?  I have Swiss as ipl.dol on my SD2SP2 card.  If I remove the SD card from SD2SP2 then it boots up like a vanilla GC, which is what I was hoping to achieve without having to pop the card out.

Ideas?  Am I confused?

**Comment by 9ary** [comment]
This is only available in iplboot r8, which has been in pre-release. PicoBoot currently uses iplboot r7. @webhdx, maybe it would be a good idea to put out a beta build? I really would appreciate if people would actually test it.

Also in general, please note that the readme documents the current, in-development version rather than the latest release, so there may be inconsistencies.

Closing because this is not an iplboot problem.

**Comment by webhdx** [comment]
Sure, let's do that. But I also need to add M.2 Loader support in the build. Just let me know which branch I should use.
