### ISSUE TITLE
[Question] Load file from DVD drive?

### ISSUE THREAD

**Issue by abreumatheus** [redolution/iplboot#39]
Hi. I would like to know if it's feasible to boot from a ipl.dol located on a DVD on the console drive.
If it is, any tips on how would I get data from the DVD?

**Comment by 9ary** [comment]
This is currently not supported, and it's unlikely to ever be for several reasons.

iplboot is already struggling to fit on some modchips due to its size, and DVD support would pull in extra code (the driver for the disc drive, as well as support for ISO9660 and the regular GCM filesystem). I suspect demand is low, so the cost to benefit ratio is poor.

Additionally, I don't want to encourage burning discs at this point. Drives are aging and using burned DVDs accelerates laser failure. We already have several peripherals which provide solid state storage, please use those (iplboot currently only supports SD cards, but m.2 loader support is on the way, along with other fun stuff).

**Comment by abreumatheus** [comment]
@9ary Your concerns are completely understandable. Thank you for the quick reply and congrats on the project.
